[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "img2ascii"
dynamic = ["version"]
description = "A Python library and CLI tool to convert images to ASCII art and pixel-perfect HTML/SVG."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "G Shreekar", email = "144794118+GShreekar@users.noreply.github.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Artistic Software",
    "Environment :: Console",
]
dependencies = [
    "numpy>=1.20.0",
    "Pillow>=9.0.0",
]
keywords = ["image", "ascii", "tool", "image to text", "cli", "image to ascii", "ascii image", "image text"]

[project.optional-dependencies]
fast = ["numba>=0.56.0"]
edges = ["scipy>=1.8.0"]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=3.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
    "hypothesis>=6.0.0",
]
all = [
    "img2ascii[fast,edges,dev]"
]

[project.scripts]
img2ascii = "img2ascii.cli.main:main"

[tool.hatch.version]
path = "src/img2ascii/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/img2ascii"]
